###############################################################################
#
# Library makefile
#
# Compiles and links mpifx in the current directory.
#
# Needs the following variables:
#     FXX: Fortran 2003 compiler
#     FXXOPT: Options for the Fortran 2003 compiler
#     M4: M4 macro processor
#     M4OPT: Options for the M4 macro processor.
#     SRCDIR: Folder where source files are located
#
###############################################################################

.SUFFIXES:
.SUFFIXES: .F90 .o

.SECONDARY: %.o

TARGETLIB = libpoisson.a

vpath % $(SRCDIR)

.PHONY: all
all: $(TARGETLIB)

include $(SRCDIR)/make.deps

$(TARGETLIB): $(objs)
	ar r $@ $^

%.f90: %.F90
	$(FPP) $(FPPOPT) $< $@

%.o: %.f90
	$(FXX) $(FXXOPT) $(INCLUDES) -c $<

.PHONY: clean realclean
clean:
	rm -f *.o

distclean: clean
	rm -f *.mod
	rm -f $(TARGETLIB)

### Local Variables:
### mode:makefile
### End:
