os: linux
dist: bionic

language: python
python: 3.7


env:
 - WITH_MPI=false
 - WITH_MPI=true

addons:
   apt:
      packages:
      - cmake
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - libscalapack-openmpi-dev
      - libarpack2-dev

install:
- echo "y" | ./utils/get_opt_externals ALL

script:
- ./utils/test/travis-ci.sh
