name: CI
on: [push, pull_request]

jobs:
  osx-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        brew install ninja arpack gcc@8
        pip3 install numpy
        echo "y" | ./utils/get_opt_externals ALL
    - name: Configure build files
      run: FC=gfortran-8 CC=gcc-8 cmake -B_build -S. -GNinja -DCMAKE_BUILD_TYPE=Debug -DFYPP_FLAGS='-DTRAVIS' -DWITH_MPI=false -DWITH_TRANSPORT=true -DWITH_DFTD3=true -DWITH_MBD=true -DWITH_ARPACK=true -DWITH_API=true -DELSI_VERSION=0 -DLAPACK_LIBRARIES="lapack"
    - name: Compile project from source
      run: ninja -C _build
    - name: Run testsuite
      run: cd _build && OMP_NUM_THREADS=2 ctest -j 2
